apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-tesseris
  namespace: default
  labels:
    app: erp-tesseris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tesseris
  template:
    metadata:
      labels:
        app: erp-tesseris
    spec:
      containers:
        - name: erp-tesseris
          image: __DOCKER_IMAGE__:__TAG__
          ports:
            - containerPort: 19091
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JWT_SECRET
            - name: JASYPT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JASYPT_PASSWORD
            - name: FILE_SERVICE_URL
              value: "http://localhost:8080/api/file"
            - name: POST_SERVICE_URL
              value: "http://localhost:9000/api/posts"
            - name: FRONTEND_URL
              value: "http://localhost:4173"
            - name: FRONTEND_ADMIN_URL
              value: "http://localhost:7001"
            - name: APP_DOMAIN
              value: "localhost"
            - name: SWAGGER_SERVER_URL
              value: "http://localhost:19091/api"
            - name: SPRING_JWT_SECRET_CODE
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JWT_SECRET
            - name: APP_DEV_MODE
              value: "true"