apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-tesseris
  namespace: default
  labels:
    app: erp-tesseris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tesseris
  template:
    metadata:
      labels:
        app: erp-tesseris
    spec:
      containers:
        - name: erp-tesseris
          image: __DOCKER_IMAGE__:__TAG__
          ports:
            - containerPort: 19091
          env:
            - name: TZ                 # ★ 타임존 설정 추가
              value: "Asia/Seoul"
            - name: JAVA_OPTS
              value: "-Duser.timezone=Asia/Seoul"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JWT_SECRET
            - name: JASYPT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JASYPT_PASSWORD
            - name: FILE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: FILE_SERVICE_URL
            - name: POST_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: POST_SERVICE_URL
            - name: ALARM_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: ALARM_SERVICE_URL
            - name: CHAT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: CHAT_SERVICE_URL
            - name: FRONTEND_URL
              value: "http://localhost:4173"
            - name: FRONTEND_ADMIN_URL
              value: "http://localhost:7001"
            - name: APP_DOMAIN
              value: "localhost"
            - name: SWAGGER_SERVER_URL
              value: "http://localhost:19091/api"
            - name: SPRING_JWT_SECRET_CODE
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JWT_SECRET
            - name: APP_DEV_MODE
              value: "true"
            - name: KAKAORESTAPIKEY
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: KAKAORESTAPIKEY
            - name: NAVER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: NAVER_EMAIL
            - name: NAVER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: NAVER_EMAIL_PASSWORD
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: AWS_SECRET_KEY
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: AWS_S3_BUCKET
            - name: TOSS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: TOSS_SECRET_KEY
          volumeMounts:
            - name: timezone-volume
              mountPath: /etc/localtime
              subPath: zoneinfo/Asia/Seoul
              readOnly: true
      volumes:
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo
            type: Directory
