server:
  port: 19091
  tomcat:
    uri-encoding: UTF-8

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ERP-project-backend

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  # ??? ??
  messages:
    encoding: UTF-8

  # DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kschost.ddns.net:30006/tesseris_db
    username: chilguy
    password: 'ictEDU1234!'


  #JWT 임시 셋팅
  jwt:
    refresh:
      cookie:
        name: refresh
      expired: 86400000
      # expired: 15000  # 정은 테스트용 15초 
    access:
      expired: 36400000
      # expired: 10000 # 정은 테스트용 10초 
      
    secret:
      code: zX9#mK2$pL7@qR5^vN3&hB6*fD1!jW8%cT4(uY0)sA2_eG5+iO9=lQ7

  # Data JPA ??
  jpa:
    show-sql: true # ????? ?????
    hibernate:
      ddl-auto: none # ??. ?? ???? DB? ???
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        dialect: org.hibernate.dialect.MariaDBDialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        org.hibernate.SQL: debug # logger? ?????
        org.hibernate.type: trace
        hibernate:
          globally_quoted_identifiers: true
          globally_quoted_identifiers_skip_column_definitions: true
          format_sql: true
          use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console


  # OAUTH ?? ???
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id:
#            client-secret:
#            scope:
#              - name
#              - email
#            client-name: Naver
#            authorization-grant-type:
#            redirect-uri:
#
#          kakao:
#            client-id:
#            client-secret:
#            scope:
#              - profile_nickname
#              - profile_image
#              - account_email
#            client-name: Kakao
#            authorization-grant-type:
#            client-authentication-method:
#            redirect-uri:
#
#          apple:
#            client-id:
#            client-secret:
#            scope:
#              - name
#              - email
#            client-name: Apple
#            authorization-grant-type:
#            client-authentication-method:
#            redirect-uri:
#
#          google:
#            client-id:
#            client-secret:
#            scope:
#              - email
#              - profile
#
#        provider:
#            naver:
#              authorization-uri: https://nid.naver.com/oauth2.0/authorize
#              token-uri: https://nid.naver.com/oauth2.0/token
#              user-info-uri: https://openapi.naver.com/v1/nid/me
#              user-name-attribute: response
#
#            kakao:
#              authorization-uri: https://kauth.kakao.com/oauth/authorize
#              token-uri: https://kauth.kakao.com/oauth/token
#              user-info-uri: https://kapi.kakao.com/v2/user/me
#              user-name-attribute: id
#
#            apple:
#              authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
#              token-uri: https://appleid.apple.com/auth/token

# AWS S3
#cloud:
#  aws:
#    credentials:
#      accessKey:
#      secretKey: 
#
#    s3:
#      bucket:
#      region:
#        static: ap-northeast-2
#      stack:
#        auto: false


logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
        bean:
          factory:
            support: DEBUG
      security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    server-url: http://localhost:19091/api
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

file-service:
  url: http://localhost:8080/api/file

post-service:
    url: http://localhost:9000/api/posts

feign:
  httpclient:
    hc5:
      enabled: true

fegin:
  school:
    appId: JAKDANG-LABS


app:
  frontend-url: http://localhost:4173
  frontend-admin-url: http://localhost:7001
  domain: localhost
  dev-mode: true

jasypt:
  encryptor:
    password: local


