apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-tesseris
  namespace: default
  labels:
    app: erp-tesseris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tesseris
  template:
    metadata:
      labels:
        app: erp-tesseris
    spec:
      containers:
        - name: erp-tesseris
          image: <DOCKER_IMAGE>:<TAG>
          ports:
            - containerPort: 19091
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JWT_SECRET
            - name: JASYPT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-tesseris-secret
                  key: JASYPT_PASSWORD 