apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-tesseris
  labels:
    app: erp-tesseris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tesseris
  template:
    metadata:
      labels:
        app: erp-tesseris
    spec:
      containers:
        - name: erp-tesseris
          image: <DOCKER_IMAGE>:<TAG>
          ports:
            - containerPort: 19091
          env:
            - name: DB_URL
              value: "${DB_URL}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
            - name: JASYPT_PASSWORD
              value: "${JASYPT_PASSWORD}" 