name: CI/CD Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          build-args: |
            PROFILE_ACTIVE=prod

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Create or update erp-tesseris-secret
        run: |
          kubectl create secret generic erp-tesseris-secret \
            --from-literal=DB_URL="${{ secrets.DB_URL }}" \
            --from-literal=DB_USER="${{ secrets.DB_USER }}" \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --from-literal=JASYPT_PASSWORD="${{ secrets.JASYPT_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Replace image tag and apply deployment
        run: |
          sed "s#__DOCKER_IMAGE__#${{ secrets.DOCKER_IMAGE }}#g" my-k8s-app/final/springboot_deployment.yaml | \
          sed "s#__TAG__#${{ github.sha }}#g" > my-k8s-app/final/springboot_deployment.generated.yaml

          kubectl apply -f my-k8s-app/final/springboot_deployment.generated.yaml

      - name: apply service
        run: |
          kubectl apply -f my-k8s-app/final/springboot_service.yaml 